### ISSUE TITLE
Dialog.done(1) failing to open file

### ISSUE THREAD

**Issue by JamesDarby345** [KhartesViewer/khartes#24] opened 2024-02-29 19:09 UTC
Im using apple silicon M2 on sonoma, and when I try and open a directory (zarr, tiff, khprj) I get "No khprj directory selected" etc. It seems to be because the dialog.done(1) is causing dialog.exec() to return 0 somehow, and thus returning. Commenting out dialog.done(1) allows me to select the folder and hit the accept button which works.

Why was that on directory entry code added in the first place? It seems like it could be removed fine, I experience nothing unexpected when double clicking in directories.

**Comment by KhartesViewer** [comment] 2024-03-01 10:03
Thanks for your bug report!  I was especially interested to learn that you are running a version of MacOS, since I currently do not have access to an Apple machine.
So, first I'll explain the reason for the directory entry code, and second, I'll ask you to download a test version of khartes to run some diagnostics, so I can better understand the behavior on MacOS.
Take, for example, the Open Project file dialog.
The dialog's default behavior (without my added directory entry code) is this: when the user double-clicks on a directory, such as `example.khprj`, the dialog will descend into the directory, showing the contents of that directory, such as `fragments` and `volumes`.  
But I want to override that behavior: if the user double-clicks on a directory whose name ends with`.khprj`, instead of descending into that directory, khartes should load the project, just as if the user had pressed the "Open selected .khprj folder" button.
On my Windows machine, if I comment out the `dialog.done(1)` line, the double-click behavior reverts to the undesired default behavior.
Of course, this default behavior is better than the misbehavior you saw on your machine before you commented out the `dialog.done(1)` line, but I'd like to get the behavior working correctly for all OSs.
Towards this end, I've created an intentionally slightly buggy version of khartes, with some diagnostics added; I'm wondering if you could do me the favor of running this version, and pasting the results here.
If you are willing to help in this way, here are the steps to follow:
* Download the latest version of the khartes repository and check out the `file-dialog-bug` branch.
* Start khartes.
* Select `Open Project...`
* Navigate to a directory that has some .khprj projects.
* Double-click on one of the projects.  I have disabled some checks, so the project should probably open (let me know if it doesn't!)
* Look for the line that starts `*** File dialog returned...` and save it somewhere.
* Again, select `Open Project...`
* Select (but don't double-click) one of the .khprj projects, and press "Open selected .khprj" button.
* Again, find `*** File dialog returned...` and save it somewhere.
* For a third time, select `Open Project...`
* Select (but don't double-click) one of the .khprj projects, and do something different than before: press the "Cancel" button.
* I have deliberately introduced a bug that should cause the project to load despite the fact that you pressed "Cancel" (let me know if it doesn't load!)
* For the third time, find `*** File dialog returned...` and save it somewhere.
* After doing all this, please paste all three `*** File dialog returned...` messages into this bug report.

Thanks for all your help with this!  I hope that the results of this testing will yield enough information to allow me to fix the bug that you discovered.

**Comment by JamesDarby345** [comment] 2024-03-01 18:42
I checked out the branch, and the behaviour is now, whenever I single click (select) the .khprj folder in the dialog, it immediately opens the project successfully, thus I couldn't do the messing around with cancel and such. Thus I can use the file dialog bug branch fine for the open project selection. The issue still exists for selecting a zarr, and probably all the other file open dialogs you didnt change.

Ill paste the terminal output here in case its useful
```
(khartes) (base) ➜  khartes git:(file-dialog-bug) ✗ python khartes.py
Loaded settings from /Users/jamesdarby/.config/khartes.org/khartes.ini
cache size 16.0 False
*** File dialog returned 0 0 1709318212.919942
Loading project from /Users/jamesdarby/Documents/VesuviusScroll/GP/khartes/khartes_project/khartes_project.khprj
Loading widget created <main_window.MainWindow.LoadingWidget object at 0x1501cd870>
Loading zarr directory /Users/jamesdarby/Documents/VesuviusScroll/scrollData/Scroll1/ome-zarr/scroll1.zarr
reading ppm header for /Users/jamesdarby/Documents/VesuviusScroll/GP/khartes/khartes_project/khartes_project.khprj/volumes/20231210121321.ppm
created ppm 20231210121321 width 12489 height 15839
Initializing project view
Could not read file /Users/jamesdarby/Documents/VesuviusScroll/GP/khartes/khartes_project/khartes_project.khprj/views.json
no cur volume set
Loading widget created <main_window.MainWindow.LoadingWidget object at 0x1501cdf30>
setting volume default parameters Scroll1
global position x 4048 y 3944 image 7188
setting callback
Loading destroyed, loading widget to close <main_window.MainWindow.LoadingWidget object at 0x1501cdf30>
Loading widget close event <main_window.MainWindow.LoadingWidget object at 0x1501cdf30>
Finished loading project from /Users/jamesdarby/Documents/VesuviusScroll/GP/khartes/khartes_project/khartes_project.khprj
Loading destroyed, loading widget to close <main_window.MainWindow.LoadingWidget object at 0x1501cd870>
Loading widget close event <main_window.MainWindow.LoadingWidget object at 0x1501cd870>
*** File dialog returned 1 1 1709318233.954078
Loading project from /Users/jamesdarby/Documents/VesuviusScroll/GP/khartes/khartes_project
Loading widget created <main_window.MainWindow.LoadingWidget object at 0x1501cdea0>
Directory /Users/jamesdarby/Documents/VesuviusScroll/GP/khartes/khartes_project/volumes does not exist
Error creating project: Directory /Users/jamesdarby/Documents/VesuviusScroll/GP/khartes/khartes_project/volumes does not exist
Initializing project view
Project file /Users/jamesdarby/Documents/VesuviusScroll/GP/khartes/khartes_project not opened: Error creating project: Directory /Users/jamesdarby/Documents/VesuviusScroll/GP/khartes/khartes_project/volumes does not exist
Loading destroyed, loading widget to close <main_window.MainWindow.LoadingWidget object at 0x1501cdea0>
Loading widget close event <main_window.MainWindow.LoadingWidget object at 0x1501cdea0>
*** File dialog returned 0 0 1709318239.421162
Loading project from /Users/jamesdarby/Documents/VesuviusScroll/GP/khartes/khartes_project/khartes_project.khprj
Loading widget created <main_window.MainWindow.LoadingWidget object at 0x1501cdea0>
Loading zarr directory /Users/jamesdarby/Documents/VesuviusScroll/scrollData/Scroll1/ome-zarr/scroll1.zarr
reading ppm header for /Users/jamesdarby/Documents/VesuviusScroll/GP/khartes/khartes_project/khartes_project.khprj/volumes/20231210121321.ppm
created ppm 20231210121321 width 12489 height 15839
Initializing project view
Could not read file /Users/jamesdarby/Documents/VesuviusScroll/GP/khartes/khartes_project/khartes_project.khprj/views.json
no cur volume set
Loading widget created <main_window.MainWindow.LoadingWidget object at 0x1501ce050>
setting volume default parameters Scroll1
global position x 4048 y 3944 image 7188
setting callback
Loading destroyed, loading widget to close <main_window.MainWindow.LoadingWidget object at 0x1501ce050>
Loading widget close event <main_window.MainWindow.LoadingWidget object at 0x1501ce050>
Finished loading project from /Users/jamesdarby/Documents/VesuviusScroll/GP/khartes/khartes_project/khartes_project.khprj
Loading destroyed, loading widget to close <main_window.MainWindow.LoadingWidget object at 0x1501cdea0>
Loading widget close event <main_window.MainWindow.LoadingWidget object at 0x1501cdea0>
```

**Comment by KhartesViewer** [comment] 2024-03-01 23:55
Thanks for all this!
Looking at the log file, it appears that you used the Open Project dialog 3 times.  The 2nd time, the results (the numbers in the "*** File Dialog returned" line) were different than the first and third times.  Are you able to recall what it was you did differently?
Thanks again for doing all this testing!

**Comment by JamesDarby345** [comment] 2024-03-02 10:52
I forgot what I did, but I managed to reproduce it with *** File dialog returned 1 1 1709376612.055844. The 2nd time/ when I get 1 1, I clicked Open selected .khprj folder on a folder that wasnt actually a .khprj folder.

**Comment by KhartesViewer** [comment] 2024-03-02 14:52
Thanks for the additional info!  I admit I'm still confused, but I made some changes to attempt to fix the problem anyway.  Could you download the latest changes in the file-dialog-bug branch, and let me know if they work?  I've fixed (or attempted to fix) the dialogs for khprj, tiff, and zarr files.  Fingers crossed...

**Comment by JamesDarby345** [comment] 2024-03-02 17:02
The current file-dialog branch is usable, I was able to load a project, ome-ZARR and .obj file.
How it worked is once a valid file was selected, the fil edialog immediately closed and opened the file. The one thing I would change is loading the ZARR. I had to open the 'popup' then select the file, then the dialog and 'popup' closed. But next time I opened the popup the same ZARR was still selected, so I could name and create it without having to reopen the file dialog.

Its no longer a breaking bug that requires me to edit the code though.

**Comment by JamesDarby345** [comment] 2024-03-02 20:24
Similar behaviour happens when creating a volume from tifs as it does when trying to load a ZARR

**Comment by KhartesViewer** [comment] 2024-03-03 10:16
One more round... 

The QFileDialog emits a directoryEntered signal whenever a directory is "entered".  In Windows (and I suppose Linux, since no one has reported problems), the signal is emitted when the user double-clicks on a directory.  In MacOS, I now realize, the signal is emitted even when the user only single-clicks on the directory.  I couldn't find this difference in behavior documented (or even discussed) anywhere, so I don't really have reason to hope that it will be different in Qt6 versus Qt5.

Anyway, I've modified the code a bit more in the file-dialog-bug branch.  It now checks (or attempts to check) whether the user is running MacOS.  If so, then the directoryEntered signal is ignored.  This means that on MacOS, the file dialog should behave the way it normally would: single-clicking highlights a directory, and double-clicking descends into a directory.  I've applied the change to project create/open/save-as, and to reading tiff and zarr files.  Please let me know if you see behavior different to what I described!  

You also mentioned that the zarr/tiff popups close immediately when you select a directory.  I couldn't figure out why this happens, and I'm hoping (for no good reason) that my other changes will somehow fix this problem.  But just in case, I added a couple more diagnostic messages.

So if you still see this problem (i.e. the popup disappears immediately when you select a directory), please immediately (before reopening the popup) copy the log messages, and maybe I'll be able to figure something out.

Thanks again!

**Comment by JamesDarby345** [comment] 2024-03-07 16:13
The create/open/save-as work as expected! But the create volume from tiff and load ZARR's are still closing. I think its perhaps because both of them open a menu, then you open the file dialog from there, so maybe the changes haven't been made to that submenu. Sorry for the delay, but I got entrenched in file storage research.

This is the only output when I select the zarr directory and the file dialog closes: On dir button clicked
file_names ['/Volumes/Corsair_8TB/Scroll1/Scroll1.zarr']

**Comment by KhartesViewer** [comment] 2024-03-09 10:52
Thanks for running these tests!
It sounds like the original problem (file dialog doesn't work correctly) is fixed.  But the new problem (load-zarr and other dialog boxes close prematurely) is not.  And the cause is a bit of a mystery to me.
The file dialogs are Qt built-ins.
On the other hand, the attach-zarr dialog (and its friends) are created and programmed by me.  And in my code, I hide the dialog only after the user presses either the "Create" or the "Cancel" button.  The visibility of the attach-zarr dialog should not be affected by anything the user does in the select-directory dialog; the select-directory dialog, in theory, does not have any control over the visibility of its parent.
So I'm making one more attempt to figure out what is going on, if you are agreeable to running one more test.
I have modified the code so that whenever the load-zarr dialog is hidden, it prints a stack trace to indicate who called its "hide" function.  I am not very optimistic that this will actually provide useful information.  The stack trace only shows the python code; it doesn't go into the C++ Qt code underneath.
Anyway, the test is pretty simple: Get the latest code on the file-dialog-bug branch, start khartes, open the attach-zarr dialog, select a directory.  Then send me anything that is printed, especially the "Traceback", if any.
Thanks for your patience!

**Comment by JamesDarby345** [comment] 2024-03-12 21:45
Well I ran the test and It worked with the ZARR data! So thats good. I did some regression testing, and all the use cases seemed to work as expected. One thing I did come across though is that if I open a set of volume cubes that have partially downloaded cubes, khartes crashes, but that is really the fault of the vol cube being essentially corrupted I imagine. I was able to load completed volume cubes in from the ZARR menu fine.

This is the console output: 
Running on Darwin
Loaded settings from /Users/jamesdarby/.config/khartes.org/khartes.ini
qt.qpa.window: Window position QRect(-2714,110 1920x1027) outside any known screen, using primary screen
cache size 16.0 False
directory entered /Users/jamesdarby/Documents/VesuviusScroll/GP/khartes/khartes_project/diagTest.khprj
ignoring because running on MacOS
File dialog returned 1 1
Loading project from /Users/jamesdarby/Documents/VesuviusScroll/GP/khartes/khartes_project/diagTest.khprj
Loading widget created <main_window.MainWindow.LoadingWidget object at 0x308fc1870>
reading header for /Users/jamesdarby/Documents/VesuviusScroll/GP/khartes/khartes_project/diagTest.khprj/volumes/Scroll2Cubes.nrrd
finished reading
gijk_starts (0, 0, 1)
1.0 2024-03-07T16:01:23.52Z 2024-03-07T16:01:23.52Z (500, 500, 3)
loading obj file /Users/jamesdarby/Documents/VesuviusScroll/GP/khartes/khartes_project/diagTest.khprj/fragments/20230507064642.obj
tf obj reader 3376 3376 6428
20230507064642 #ffffff (3376, 3) (3376, 2) (6428, 3)
Initializing project view
no cur volume set
Loading widget created <main_window.MainWindow.LoadingWidget object at 0x308fc1d80>
reading data from /Users/jamesdarby/Documents/VesuviusScroll/GP/khartes/khartes_project/diagTest.khprj/volumes/Scroll2Cubes.nrrd for Scroll2Cubes
finished reading
(3, 500, 500) (500, 3, 500) (500, 3, 500)
Loading destroyed, loading widget to close <main_window.MainWindow.LoadingWidget object at 0x308fc1d80>
Loading widget close event <main_window.MainWindow.LoadingWidget object at 0x308fc1d80>
Finished loading project from /Users/jamesdarby/Documents/VesuviusScroll/GP/khartes/khartes_project/diagTest.khprj
Loading destroyed, loading widget to close <main_window.MainWindow.LoadingWidget object at 0x308fc1870>
Loading widget close event <main_window.MainWindow.LoadingWidget object at 0x308fc1870>
On dir button clicked
zarr/tiff directory entered /Volumes/16TB_RAID_0
ignoring because running MacOS
zarr/tiff directory entered /Volumes/16TB_RAID_0/Scroll2
ignoring because running MacOS
zarr/tiff directory entered /Volumes/16TB_RAID_0/Scroll2/Scroll2.zarr
ignoring because running MacOS
file_names ['/Volumes/16TB_RAID_0/Scroll2/Scroll2.zarr']
/Volumes/16TB_RAID_0/Scroll2/Scroll2.zarr S2ZARR #ff00ff
unloading data for Scroll2Cubes
Loading widget created <main_window.MainWindow.LoadingWidget object at 0x308fc1870>
Loading zarr directory /Volumes/16TB_RAID_0/Scroll2/Scroll2.zarr
Loading destroyed, loading widget to close <main_window.MainWindow.LoadingWidget object at 0x308fc1870>
Loading widget close event <main_window.MainWindow.LoadingWidget object at 0x308fc1870>
Loading widget created <main_window.MainWindow.LoadingWidget object at 0x308fc1900>
setting volume default parameters S2ZARR
global position x 5992 y 5056 image 7214
setting callback
Loading destroyed, loading widget to close <main_window.MainWindow.LoadingWidget object at 0x308fc1900>
Loading widget close event <main_window.MainWindow.LoadingWidget object at 0x308fc1900>
Hiding self; spontaneous: False
Traceback:
  File "/Users/jamesdarby/Documents/VesuviusScroll/GP/khartes/khartes.py", line 23, in <module>
    app.exec()
  File "/Users/jamesdarby/Documents/VesuviusScroll/GP/khartes/zarr_loader.py", line 304, in onGoButtonClicked
    self.hide()
  File "/Users/jamesdarby/Documents/VesuviusScroll/GP/khartes/zarr_loader.py", line 316, in hideEvent
    traceback.print_stack()
End of traceback

**Comment by KhartesViewer** [comment] 2024-03-21 03:04
Thanks for all your help on testing this!  I have merged the fixes into the main branch.

**Closed as completed by KhartesViewer** 2024-03-21 03:04 UTC
